### PR TITLE
FIX Travis PHP versions

### PR DESCRIPTION
**Pull request by dnsl48**

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Do you want to look into the travis failure (from framework) before this is merged?

**Comment by dnsl48** [comment]
yes, I'll have a look

**Comment by dnsl48** [comment]
here's the fix - https://github.com/silverstripe/silverstripe-framework/pull/9123

**Comment by dnsl48** [comment]
@ScopeyNZ it's been handled https://github.com/silverstripe/recipe-core/pull/46

**Pull request merged**
