### PR TITLE
.travis.yml | fix the required versions

### PR DESCRIPTION
**Pull request by dnsl48**
## Related issues

* https://github.com/silverstripe/silverstripe-framework/issues/8522

### CODE REVIEW

**Comment by dnsl48** [comment]
the tests fail isn't introduced by this PR

**Comment by ScopeyNZ** [comment]
Is this a merge up?

**Comment by dnsl48** [comment]
this is a patch on top of a merge-up

**Comment by dnsl48** [comment]
That's the particular patch - https://github.com/silverstripe/recipe-core/pull/39/commits/910a1ee0b284e8b5d16936c3a8f26f7fa17f632d

**Comment by ScopeyNZ** [comment]
Something weird is happening here though. These commits should be in 4.

**Comment by dnsl48** [comment]
haha, that looks like a github glitch. All the commit hashes are the same as in 4

**Comment by dnsl48** [comment]
updated

**Comment by robbieaverill** [comment]
I think the Postgres builds are fixed elsewhere, if not they aren’t part of this recipe so shouldn’t block merge

**Pull request merged**
